[2025-04-26T01:12:43.085+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T01:12:43.107+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-04-26T01:12:14.208379+00:00 [queued]>
[2025-04-26T01:12:43.119+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-04-26T01:12:14.208379+00:00 [queued]>
[2025-04-26T01:12:43.121+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-26T01:12:43.289+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_user> on 2025-04-26 01:12:14.208379+00:00
[2025-04-26T01:12:43.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2323) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-26T01:12:43.311+0000] {standard_task_runner.py:72} INFO - Started process 2325 to run task
[2025-04-26T01:12:43.309+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2025-04-26T01:12:14.208379+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpok4670s9']
[2025-04-26T01:12:43.315+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask process_user
[2025-04-26T01:12:43.385+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user manual__2025-04-26T01:12:14.208379+00:00 [running]> on host bb0d27cab5a5
[2025-04-26T01:12:43.478+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T01:12:14.208379+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T01:12:14.208379+00:00'
[2025-04-26T01:12:43.483+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-26T01:12:43.537+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-26T01:12:43.553+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-26T01:12:43.554+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, run_id=manual__2025-04-26T01:12:14.208379+00:00, execution_date=20250426T011214, start_date=20250426T011243, end_date=20250426T011243
[2025-04-26T01:12:43.614+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-26T01:12:43.650+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-26T01:12:43.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
