[2025-04-26T01:32:53.752+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-26T01:32:53.786+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-04-26T01:32:17.206710+00:00 [queued]>
[2025-04-26T01:32:53.804+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user manual__2025-04-26T01:32:17.206710+00:00 [queued]>
[2025-04-26T01:32:53.805+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-26T01:32:54.083+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_user> on 2025-04-26 01:32:17.206710+00:00
[2025-04-26T01:32:54.111+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2613) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-26T01:32:54.126+0000] {standard_task_runner.py:72} INFO - Started process 2615 to run task
[2025-04-26T01:32:54.127+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2025-04-26T01:32:17.206710+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmph05n9lg3']
[2025-04-26T01:32:54.145+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask process_user
[2025-04-26T01:32:54.231+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user manual__2025-04-26T01:32:17.206710+00:00 [running]> on host bb0d27cab5a5
[2025-04-26T01:32:54.421+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T01:32:17.206710+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T01:32:17.206710+00:00'
[2025-04-26T01:32:54.427+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-26T01:32:54.514+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-26T01:32:54.531+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-26T01:32:54.532+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, run_id=manual__2025-04-26T01:32:17.206710+00:00, execution_date=20250426T013217, start_date=20250426T013253, end_date=20250426T013254
[2025-04-26T01:32:54.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-26T01:32:54.657+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-26T01:32:54.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
